# v1
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.2.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.950"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
        types: [ python ]
        args: [ --py37-plus ]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        args: [ --line-length=88, --target-version=py310 ]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        args: [ --in-place, --remove-duplicate-keys ]

      - id: flake8
        name: flake8
        entry: flake8
        exclude: ^alembic/
        language: system
        types: [ python ]
        args: [
          "--ignore=E203,U100,W503,FI58,PT013,E712",
          "--max-line-length=88",
          "--per-file-ignores=tests/*.py:S101"

        ]

      - id: pyupgrade
        name: pyupgrade
        entry: pyupgrade
        language: system
        types: [ python ]
        args: [ --py37-plus ]

      - id: yesqa
        name: yesqa
        entry: yesqa
        language: system
        types: [ python ]